// set my main body component as my my main state that can be over written with a previous button and using this setState

import React from 'react';
import './Comp CSS/WorkHistory.css'

class WorkHistory extends React.Component {
    constructor(props) {
        super(props)
    
     
        this.state = {
            title : "WORK HISTORY",
            timeFrame: "Jan 2017 to Apr 2019 - Merchandise Controller/Buyer - Littlewoods Clearance (Shop Direct Group) Manchester",
            mainText: "Managed £40m stock file through the business generated by Shop Direct by means of planning and allocation through our commercial channels\n Produced and maintained an accurate Open to Buy (OTB) of our externally purchased merchandise. For accurate reporting and real time budget target updates most recently for £2.0m at Sales and £850k cost\n Primarily represented Buying & Merchandising in Management meetings and briefings as required\n Deputising for the Commercial General Manager when required by the business\nPro-actively controlled aspects of Online designated stock in conjunction with online colleagues to ensure correct forecast of quantities and stock is in the business and deployed correctly\n Managed Product Recall notice/issues from Shop Direct Group within LWC\nPurchase external product from suppliers to achieve sales targets across mens apparel and all footwear departments\nResponsible directly for total sales in stores of £725k with a cost of £315k\nResponsible directly for total sales online of £220k with a cost of £110kn\nWorked with B&M Team Warehousing to ensure external product cycle is as efficient as possible from purchase to shop floor\nEnsured External Products have passed QA and have necessary paperwork signed off.",
            }
        
        }

        WorkHistoryPrt2 () {
            this.setState({
            title: "WORK HISTORY",
            timeFrame: "July 2011 to Jan 2017 - Wholesale Manager/Buyer Littlewoods Clearance (Shop Direct Group) - Manchester",
            mainText: "Yeah boy!",
            })
        } 
    
        WorkHistoryPrt3 () {
            this.setState({
            title: "WORK HISTORY",
            timeFrame: "June 2005 to July 2011 - Wholesale Manager Littlewoods Clearance (Shop Direct Group) – Manchester",
            mainText: "Yeah boy 2!",
            })
        } 
        WorkHistoryPrt4 () {
            this.setState({
            title: "WORK HISTORY",
            timeFrame: "March 2003 to June 2005 - Distribution Assistant Bargain Crazy (Shop Direct) - Manchester",
            mainText: "Yeah boy 3!",
            })
        } 
    

    

    render() {
        return (
            <div className = "workH">
                <h2>{this.state.title}</h2>
                
                <h3>{this.state.timeFrame}</h3>
                
                <p>{this.state.mainText}</p>

            <div className = "buttondiv">
            <button className = "button" onClick = {()=>this.WorkHistoryPrt2()}>More Recent Work History</button>
            <button className = "button" onClick = {()=>this.WorkHistoryPrt3()}>Previous Work History</button>
            </div>

            
            <div>
            <p className = "timeline" >
                <p className = "p1">2019</p>
                <p>Timeline</p>
                <p className = "p3">2000</p>
                </p>
            </div>
            
            </div>
        )
    }
}

export default WorkHistory;