// set my main body component as my my main state that can be over written with a previous button and using this setState

import React from 'react';
import './Comp CSS/WorkHistory.css'

class WorkHistory extends React.Component {
    constructor(props) {
        super(props)

     
this.state = {
    title : "WORK HISTORY",
    timeFrame: "Jan 2017 to Apr 2019 - Merchandise Controller/Buyer - Littlewoods Clearance (Shop Direct Group) Manchester",
    mainText: <ul><li>Managed £40m stock file through the business generated by Shop Direct by means of planning and allocation through our commercial channels</li><li>Produced and maintained an accurate Open to Buy (OTB) of our externally purchased merchandise. For accurate reporting and real time budget target updates most recently for £2.0m at Sales and £850k cost</li><li>Primarily represented Buying & Merchandising in Management meetings and briefings as required</li><li>Deputising for the Commercial General Manager when required by the business</li><li>Pro-actively controlled aspects of Online designated stock in conjunction with online colleagues to ensure correct forecast of quantities and stock is in the business and deployed correctly</li><li>Managed Product Recall notice/issues from Shop Direct Group within LWC</li><li>Purchase external product from suppliers to achieve sales targets across mens apparel and all footwear departments</li><li>Responsible directly for total sales in stores of £725k with a cost of £315k</li><li>Responsible directly for total sales online of £220k with a cost of £110k</li><li>Worked with B&M Team Warehousing to ensure external product cycle is as efficient as possible from purchase to shop floor</li><li>Ensured External Products have passed QA and have necessary paperwork signed off</li></ul>,
    }
}

WorkHistoryPrt2 () {
    this.setState({
    title: "WORK HISTORY",
    timeFrame: "July 2011 to Jan 2017 - Wholesale Manager/Buyer Littlewoods Clearance (Shop Direct Group) - Manchester",
    mainText: <ul><li>Purchase external product from suppliers to achieve sales targets across mens apparel and all footwear departments</li><li>Responsible directly for total sales in stores of £800k with a cost of £342k</li><li>Responsible directly for total sales online of £150k with a cost of £76k</li><li>Wholesale achieve sales of £225k</li><li>Produce and maintain an accurate OTB of the External Merchandise due in the business. For accurate reporting and real time budget target updates circa £2.6m sales and £1.2m cost</li><li>Manage procure orders inline with the budget for some areas of NMP stock into the stores and warehousing circa £100k cost</li></ul>
    })
} 

WorkHistoryPrt3 () {
    this.setState({
    title: "WORK HISTORY",
    timeFrame: "June 2005 to July 2011 - Wholesale Manager Littlewoods Clearance (Shop Direct Group) – Manchester",
    mainText: <ul><li>Led the Wholesale Team annually over achieving sales targets in excess of £5m with a stock value over £55m into the jobbing market and achieving over £1m profit</li><li>Directly responsible for sales over £22m stock value of the above and £2m sales and £400k profit of the teams KPIs</li><li>Established strong whole sale relationships to maintain sales and profit margins and annually increased new business participation each year by around 2.5% thus increasing profit margins year on year.</li><li>Managed team of three direct reports within the wholesale team</li></ul>,
    })
} 
WorkHistoryPrt4 () {
    this.setState({
    title: "WORK HISTORY",
    timeFrame: "March 2003 to June 2005 - Distribution Assistant Bargain Crazy (Shop Direct) - Manchester",
    mainText: <ul><li>Arranged with 46 stores their individual deliveries</li><li>Produced delivery plans each week and PODs for stores and MI reporting</li><li>Worked a weekly capacity report for MI reporting on effectiveness of the fleet</li></ul>,
    })
} 


render() {
    return (
        <div className = "workH">
            <h2>{this.state.title}</h2>
            
            <h3>{this.state.timeFrame}</h3>
            
            <p>{this.state.mainText}</p>

        <div className = "buttondiv">
        <button className = "button" onClick = {()=>this.WorkHistoryPrt2()}>More Recent Work History</button>
        <button className = "button" onClick = {()=>this.WorkHistoryPrt3()}>Previous Work History</button>
        </div>

        
        <div>
        <p className = "timeline" >
            <p className = "p1">2019</p>
            <p>Timeline</p>
            <p className = "p3">2000</p>
            </p>
        </div>
        
        </div>
    )
}
}

export default WorkHistory;